target 'SportsYap!' do
  use_frameworks!
	pod 'ACFloatingTextfield', '~> 0.1'
	pod 'Alamofire', '~> 4.4'
	pod 'SZTextView', '~> 1.3'
	pod 'SwiftyJSON', '~> 3.1'
	pod 'TPKeyboardAvoiding', '~> 1.3'
	pod 'MBProgressHUD', '~> 1.0'
    pod 'FacebookLogin'
    pod 'SDWebImage', '~> 4.0'
    pod 'GooglePlacesAPI', '~> 1.1'
    pod 'GooglePlaces', '~> 2.3'
end

